#!/bin/bash
#
# /etc/rc.d/init.d/shadowbound
#
# Shadowbound
#
# chkconfig: 2345 80 20
# description: Shadowbound daemon used to start the server and keep it updated
# processname: StarboundServer
# config: /etc/shadowbound/shadowbound.cfg

### BEGIN INIT INFO
# Provides:          Shadowbound deamon
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Shadowbound deamon
# Description:       Shadowbound daemon used to start the server and keep it updated
#
### END INIT INFO

# Using the lsb functions to perform the operations.
. /etc/rc.d/init.d/functions

# Global variables
source /etc/shadowbound/shadowbound.cfg

NAME="StarboundServer"
LOGFILE="${logdir}/${NAME}.log"
DAEMON="/usr/bin/shadowbound"

GREEN="\\033[1;32m"
RED="\\033[1;31m"
NORMAL="\\033[0;39m"

set -e

# If the daemon is not there, then exit.
test -x $DAEMON || exit 5

case "$1" in
	start)
		log_daemon_msg "Starting" "$NAME"
		ulimit -n 100000
		su -s /bin/sh -c "$DAEMON start" $steamcmd_user > /dev/null
		sleep 5
		PID=`ps -ef | grep $NAME | grep -v grep | awk '{print $2}'`
		
		if  [ -n "$PID" ];  then
			echo "$PID" >/var/run/shadowbound.pid
			touch /var/lock/subsys/shadowbound
			echo "[" "$GREEN" " OK " "$NORMAL" "]"
			exit 0
		else
			echo "[" "$RED" " FAILED " "$NORMAL" "]"
			exit 1
		fi
	;;
	stop)
		log_daemon_msg "Stopping" "$NAME"
		su -s /bin/sh -c "$DAEMON stop" $steamcmd_user > /dev/null
		sleep 5
		PID=`ps -ef | grep $NAME | grep -v grep | awk '{print $2}'`
		
		if  [ -n "$PID" ];  then
			echo "[" "$RED" " FAILED " "$NORMAL" "]"
			exit 1
		else
		echo "[" "$GREEN" " OK " "$NORMAL" "]"
			rm -f /var/lock/subsys/shadowbound
			rm /var/run/shadowbound.pid
			exit 0
		fi
	;;
	restart)
		echo -n "Restarting $NAME: "
		ulimit -n 100000
		su -s /bin/sh -c "$DAEMON restart" $steamcmd_user > /dev/null
		echo "OK"
	;;
	status)
		su -s /bin/sh -c "$DAEMON status" $steamcmd_user
		exit 0
	;;
	*)
		# For invalid arguments, print the usage message.
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
	;;
esac
