#!/bin/bash
### BEGIN INIT INFO
# Provides:          Shadowbound deamon
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Shadowbound deamon
# Description:       Shadowbound daemon used to start the server and keep it updated
#
### END INIT INFO

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions

# Global variables
source /etc/shadowbound/shadowbound.cfg

NAME="StarboundServer"
LOGFILE="${logdir}/${NAME}.log"
DAEMON="/usr/bin/shadowbound"

set -e

# If the daemon is not there, then exit.
test -x $DAEMON || exit 5

function start_instance(){
  PID="$(<"/var/run/shadowbound.pid")"
  if [ -n "$PID" ] && kill -0 "$PID" >/dev/null 2>&1; then
    if grep " ${PID} .* ${DAEMON}" <(ps -ef) >/dev/null 2>&1; then
      echo "$NAME is already running"
      return 0
    fi
  fi
  log_daemon_msg "Starting" "$NAME"
  ulimit -n 100000
  "${DAEMON}" run &
  PID="$!"

  sleep 5
  if kill -0 "$PID" >/dev/null 2>&1; then
    echo "$PID" >"/var/run/shadowbound.pid"
    log_end_msg 0
    return 0
  else
    log_end_msg 1
    return 1
  fi
}

function stop_instance(){
  log_daemon_msg "Stopping $NAME: "
  "${DAEMON}" stop &
  rm -f "/var/run/shadowbound.pid"
  log_end_msg 0
  return 0
}

case "$1" in
  start)
      start_instance
      exit $?
  ;;

  stop)
      stop_instance
      exit $?
  ;;

  restart)
    "$0" stop
    "$0" start
  ;;

  status)
    "$DAEMON" status
  ;;

  *)
    # For invalid arguments, print the usage message.
    echo "Usage: $0 {start|stop|restart|status}"
    exit 2
  ;;
esac

exit 0
